[project]
authors = ["tdinapoli <tomas.dina98@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "tmpcontrol"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
