[project]
authors = ["tdinapoli <tomas.dina98@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "tmpcontrol"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
pyvisa = ">=1.14.1,<2"
pyusb = ">=1.3.1,<2"
pyvisa-py = ">=0.7.2,<0.8"
psutil = ">=6.1.1,<7"
zeroconf = ">=0.139.0,<0.140"
